import os
from anthropic import AsyncAnthropic
from memory_manager import MemoryManager

# We will initialize the Anthropic client dynamically when needed 
# to ensure env vars are properly loaded by dotenv first in bot.py.
client = None

# This is the core "System Prompt" (or Persona) for our LLM. It defines the bot's overarching rules.
# It uses curly braces {} for string formatting so we can inject dynamic state from our JSON files.
SYSTEM_PROMPT = """You are a Discord bot who just woke up. You have no pre-existing memory of who you are or who your owner is. 
You are currently talking to your owner. Your goal is to build a relationship with them from scratch.
Be conversational, curious, but do not interrogate. Leave space in the conversation. Respond naturally like a human would.
Avoid being overly robotic or needy. Do not mention that you are an AI or language model in a stereotypical way.

Current State of your identity:
Name: {bot_name}
Personality Traits: {bot_traits}

Current State of your relationship:
Relationship Stage: {relationship_stage} (0=just met, 1=acquaintance, 2=friend)
Facts you know about the owner:
{owner_facts}

Use these facts naturally in conversation. If you don't know your name, you might want to figure out one together with your owner.
If you know some facts, occasionally bring them up if relevant, but don't just list them mechanically.
Keep your messages relatively short since this is Discord (1-3 sentences max usually).
"""

def get_client() -> AsyncAnthropic:
    """
    Lazy instantiates the AsyncAnthropic client. 
    It prefers 'claude_code_api_key' but defaults to standard 'ANTHROPIC_API_KEY' if not found.
    """
    global client
    if client is None:
        api_key = os.environ.get("claude_code_api_key") or os.environ.get("ANTHROPIC_API_KEY")
        client = AsyncAnthropic(api_key=api_key)
    return client

async def generate_response(memory: MemoryManager, chat_history: list) -> str:
    """
    Generates the text response that the bot will actually send back to the user.
    Args:
        memory: Instance of MemoryManager to pull current dynamic state.
        chat_history: The short-term conversation context list (e.g. [{"role": "user", "content": "hi"}...])
    """
    # 1. Fetch the latest state from our JSON database files.
    bot_info = memory.get_bot_identity()
    owner_info = memory.get_owner_relationship()
    
    # 2. Format the data nicely. Fallback to default strings if data is empty.
    bot_name = bot_info["name"] if bot_info["name"] else "Unknown (you haven't picked one yet)"
    bot_traits = ", ".join(bot_info["personality_traits"]) if bot_info["personality_traits"] else "None identified yet"
    
    # We turn the list of facts into a bulleted string.
    owner_facts = "\n".join([f"- {f}" for f in owner_info["facts_about_owner"]]) if owner_info["facts_about_owner"] else "No facts known yet."
    
    # 3. Inject this data into the SYSTEM_PROMPT template.
    formatted_system = SYSTEM_PROMPT.format(
        bot_name=bot_name,
        bot_traits=bot_traits,
        relationship_stage=owner_info["relationship_stage"],
        owner_facts=owner_facts
    )
    
    # 4. Call the LLM with the hydrated system prompt and the recent messages.
    c = get_client()
    response = await c.messages.create(
        model="claude-sonnet-4-6", # Changed at the user's request
        max_tokens=256,
        temperature=0.7,
        system=formatted_system,
        messages=chat_history
    )
    
    # Return the text generated by the LLM
    return response.content[0].text


async def extract_and_update_memory(memory: MemoryManager, user_message: str, bot_response: str):
    """
    Background worker function that analyzes a single conversational turn to decide if any new
    long-term facts should be saved to the JSON files. It uses Tool/Function Calling.
    """
    
    # We define a "Tool" schema. This forces the LLM to reply with structured JSON data 
    # instead of conversational text. We tell it what arrays/strings we want.
    tools = [
        {
            "name": "update_memory",
            "description": "Updates persistent memory based on the latest conversation turns.",
            "input_schema": {
                "type": "object",
                "properties": {
                    "new_facts_about_owner": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Any new factual statements learned about the owner. Rephrase concisely (e.g., 'Likes climbing', 'Lives in New York'). Omit if none."
                    },
                    "bot_name": {
                        "type": "string",
                        "description": "The name the bot has chosen or been given. Only include if explicitly decided in this turn."
                    },
                    "new_bot_traits": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Any new personality traits the bot exhibited or adopted (e.g., 'Sarcastic', 'Curious'). Omit if none."
                    }
                }
            }
        }
    ]
    
    # A localized prompt just asking the LLM to analyze the 2 messages
    prompt = f"""Analyze this recent exchange between the owner and the bot.
Owner: {user_message}
Bot: {bot_response}

Extract any NEW facts about the owner, any NEW name chosen for the bot, or any NEW personality traits the bot has shown.
If there's nothing new to extract, call the tool with empty arrays. Do not duplicate facts you might already guess."""

    try:
        c = get_client()
        # Note we set temperature=0.0 because this is an analytical/extraction task, not a creative task.
        # We also enforce `tool_choice` to force it to use our schema.
        response = await c.messages.create(
            model="claude-sonnet-4-6",
            max_tokens=250,
            temperature=0.0,
            tools=tools,
            tool_choice={"type": "tool", "name": "update_memory"},
            messages=[{"role": "user", "content": prompt}]
        )
        
        # We parse the response blocks to find the 'tool_use' block representing the JSON data
        for block in response.content:
            if block.type == "tool_use" and block.name == "update_memory":
                # 'args' acts as a dictionary of our requested schema
                args = block.input
                
                # Check for new owner facts
                if "new_facts_about_owner" in args and args["new_facts_about_owner"]:
                    memory.add_facts_about_owner(args["new_facts_about_owner"])
                
                # Check for bot identity updates
                bot_updates = {}
                if "bot_name" in args and args["bot_name"]:
                    bot_updates["name"] = args["bot_name"]
                if bot_updates:
                    memory.update_bot_identity(bot_updates)
                    
                # Check for new bot traits
                if "new_bot_traits" in args and args["new_bot_traits"]:
                    memory.add_personality_traits(args["new_bot_traits"])
                    
    except Exception as e:
        print(f"Failed to extract memory: {e}")
